### ISSUE TITLE
Failed to start bean 'zeebeClientLifecycle'; nested exception is java.lang.NullPointerException

### ISSUE THREAD

**Issue by PekopT** [zeebe-io/zeebe-simple-monitor#137]
Hi! 

Trying to run zeebe-simple-monitor with such docker-compose

```
    zeebe_broker:
        image: camunda/zeebe:0.23.1
        environment:
            - ZEEBE_LOG_LEVEL=debug
        ports:
            - "26500:26500"
            - "9601:9600"
            - "5701:5701"
        volumes:
            - ./ci/zeebe/zeebe-hazelcast-exporter-0.8.0-alpha2-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
            - ./ci/zeebe/broker.yaml:/usr/local/zeebe/config/application.yaml
        depends_on:
            elasticsearch: { condition: service_healthy }
        networks:
            - site_ru

    zeebe_monitor:
        image: camunda/zeebe-simple-monitor:latest
        environment:
          - zeebe.client.broker.contactPoint=zeebe_broker:26500
          - zeebe.worker.hazelcast.connection=zeebe_broker:5701
        ports:
            - "8082:8082"
        depends_on:
            - zeebe_broker
        networks:
            - site_ru
```

getting this log and stack-trace: 
```
___                 __
 _/  _  _ |_   _   (_  .  _   _  |  _   |\/|  _   _  . |_  _   _
/__ (- (- |_) (-   __) | ||| |_) | (-   |  | (_) | ) | |_ (_) |
                             |

================================================================
                                

2020-04-28 09:23:35.406  INFO 1 --- [  restartedMain] io.zeebe.monitor.ZeebeSimpleMonitorApp   : Starting ZeebeSimpleMonitorApp on d79736b97c15 with PID 1 (/app/classes started by root in /)
2020-04-28 09:23:35.413 DEBUG 1 --- [  restartedMain] io.zeebe.monitor.ZeebeSimpleMonitorApp   : Running with Spring Boot v2.2.6.RELEASE, Spring v5.2.5.RELEASE
2020-04-28 09:23:35.414  INFO 1 --- [  restartedMain] io.zeebe.monitor.ZeebeSimpleMonitorApp   : No active profile set, falling back to default profiles: default
2020-04-28 09:23:48.054  INFO 1 --- [  restartedMain] i.z.monitor.zeebe.ZeebeHazelcastService  : Connecting to Hazelcast 'zeebe_broker:5701'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/app/libs/hazelcast-3.12.6.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-04-28 09:23:49.683  INFO 1 --- [  restartedMain] i.z.monitor.zeebe.ZeebeHazelcastService  : Importing records from Hazelcast...
2020-04-28 09:23:49.952  INFO 1 --- [  restartedMain] i.z.h.connect.java.ZeebeHazelcast        : Read from ringbuffer 'zeebe' starting from sequence '0'
2020-04-28 09:23:53.504  INFO 1 --- [  restartedMain] i.z.h.connect.java.ZeebeHazelcast        : Closing. Stop reading from ringbuffer. Current sequence: '0'
2020-04-28 09:23:53.800 ERROR 1 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'zeebeClientLifecycle'; nested exception is java.lang.NullPointerException: target
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at io.zeebe.monitor.ZeebeSimpleMonitorApp.main(ZeebeSimpleMonitorApp.java:39) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.2.6.RELEASE.jar:2.2.6.RELEASE]
Caused by: java.lang.NullPointerException: target
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-28.2-jre.jar:na]
        at io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(AbstractManagedChannelImplBuilder.java:185) ~[grpc-core-1.28.1.jar:1.28.1]
        at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:136) ~[grpc-netty-1.28.1.jar:1.28.1]
        at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:131) ~[grpc-netty-1.28.1.jar:1.28.1]
        at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:117) ~[grpc-netty-1.28.1.jar:1.28.1]
        at io.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:122) ~[zeebe-client-java-0.23.0.jar:0.23.0]
        at io.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:78) ~[zeebe-client-java-0.23.0.jar:0.23.0]
        at io.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:257) ~[zeebe-client-java-0.23.0.jar:0.23.0]
        at io.zeebe.spring.client.config.ZeebeClientSpringConfiguration.lambda$zeebeClientObjectFactory$0(ZeebeClientSpringConfiguration.java:39) ~[spring-zeebe-0.22.0.jar:0.22.0]
        at io.zeebe.spring.util.ZeebeAutoStartUpLifecycle.start(ZeebeAutoStartUpLifecycle.java:52) ~[spring-zeebe-util-0.22.0.jar:0.22.0]
        at io.zeebe.spring.client.ZeebeClientLifecycle.start(ZeebeClientLifecycle.java:47) ~[spring-zeebe-0.22.0.jar:0.22.0]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        ... 19 common frames omitted
```

problem persists with all this hazelcast exporters 
- zeebe-hazelcast-exporter-0.8.0-alpha1-jar-with-dependencies.jar
- zeebe-hazelcast-exporter-0.8.0-alpha2-jar-with-dependencies.jar
- zeebe-hazelcast-exporter-0.8.0-jar-with-dependencies.jar
- zeebe-hazelcast-exporter-0.9.0-alpha1-jar-with-dependencies.jar

Broker logs:

```
2020-04-28 09:30:47.655 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [3/11]: command api transport started in 736 ms
2020-04-28 09:30:47.656 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [4/11]: command api handler
2020-04-28 09:30:47.763 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [4/11]: command api handler started in 107 ms
2020-04-28 09:30:47.765 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [5/11]: subscription api
2020-04-28 09:30:47.905 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [5/11]: subscription api started in 140 ms
2020-04-28 09:30:47.906 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [6/11]: embedded gateway
2020-04-28 09:30:47.947 [] [main] INFO  io.zeebe.gateway - Version: 0.23.1
2020-04-28 09:30:47.949 [] [main] INFO  io.zeebe.gateway - Starting gateway with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "port" : 26500,
    "minKeepAliveInterval" : "PT30S"
  },
  "cluster" : {
    "contactPoint" : "172.18.0.8:26502",
    "requestTimeout" : "PT15S",
    "clusterName" : "zeebe-cluster",
    "memberId" : "gateway",
    "host" : "172.18.0.8",
    "port" : 26502
  },
  "threads" : {
    "managementThreads" : 1
  },
  "monitoring" : {
    "enabled" : false,
    "host" : "172.18.0.8",
    "port" : 9600
  },
  "security" : {
    "enabled" : false,
    "certificateChainPath" : null,
    "privateKeyPath" : null
  },
  "enable" : true
}
2020-04-28 09:30:48.507 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [6/11]: embedded gateway started in 599 ms
2020-04-28 09:30:48.518 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services
2020-04-28 09:30:51.311 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [7/11]: cluster services started in 2793 ms
2020-04-28 09:30:51.313 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [8/11]: topology manager
2020-04-28 09:30:51.318 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [8/11]: topology manager started in 5 ms
2020-04-28 09:30:51.321 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [9/11]: metric's server
2020-04-28 09:30:51.359 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [9/11]: metric's server started in 36 ms
2020-04-28 09:30:51.359 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [10/11]: leader management request handler
2020-04-28 09:30:51.373 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [10/11]: leader management request handler started in 12 ms
2020-04-28 09:30:51.374 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 [11/11]: zeebe partitions
2020-04-28 09:30:51.393 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1
2020-04-28 09:30:51.543 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {} and terms {}.
2020-04-28 09:30:51.742 [] [main] DEBUG io.zeebe.broker.exporter - Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, workflowInstance=true, workflowInstanceCreation=false, workflowInstanceSubscription=false, ignoreVariablesAbove=8191}, bulk=BulkConfiguration{delay=5, size=1000}, authentication=AuthenticationConfiguration{username='null'}}
2020-04-28 09:30:51.899 [] [main] DEBUG io.zeebe.broker.exporter - Starting exporter with configuration: [port=5701, name=zeebe, enabledValueTypes=JOB,WORKFLOW_INSTANCE,DEPLOYMENT,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION, enabledRecordTypes=, capacity=-1, timeToLiveInSeconds=-1, format=protobuf]
2020-04-28 09:30:51.937 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Removing follower partition service for partition PartitionId{id=1, group=raft-partition}
2020-04-28 09:30:51.961 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Partition role transitioning from null to LEADER
2020-04-28 09:30:51.970 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.broker.system - Installing leader partition service for partition PartitionId{id=1, group=raft-partition}
2020-04-28 09:30:52.418 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Available snapshots: []
2020-04-28 09:30:53.069 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams.snapshot - Opened database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'.
2020-04-28 09:30:53.277 [Broker-0-LogStream-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
2020-04-28 09:30:53.311 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
2020-04-28 09:30:53.746 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@498ac464)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@37b093ee, configuration: Configuration(false)]
2020-04-28 09:30:53.995 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
2020-04-28 09:30:54.033 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@af67927)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@6f828047, configuration: Configuration(false)]
2020-04-28 09:30:54.068 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@46c891a7)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@3fb709e9, configuration: Configuration(false)]
2020-04-28 09:30:54.420 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
2020-04-28 09:30:54.505 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] DEBUG io.zeebe.broker.system - All partitions are installed. Broker is ready!
2020-04-28 09:30:54.513 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 partitions [1/1]: partition 1 started in 3117 ms
2020-04-28 09:30:54.516 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 3122 ms.
2020-04-28 09:30:54.517 [] [main] DEBUG io.zeebe.broker.system - Bootstrap Broker-0 [11/11]: zeebe partitions started in 3139 ms
2020-04-28 09:30:54.521 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovered exporter 'Broker-0-Exporter-1' from snapshot at lastExportedPosition -1
2020-04-28 09:30:54.523 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'elasticsearch'
2020-04-28 09:30:54.521 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 11 steps in 15431 ms.
2020-04-28 09:30:54.525 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter.elasticsearch - Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, workflowInstance=true, workflowInstanceCreation=false, workflowInstanceSubscription=false, ignoreVariablesAbove=8191}, bulk=BulkConfiguration{delay=5, size=1000}, authentication=AuthenticationConfiguration{username='null'}}
2020-04-28 09:30:54.531 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Configure exporter with id 'hazelcast'
2020-04-28 09:30:54.531 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter.hazelcast - Starting exporter with configuration: [port=5701, name=zeebe, enabledValueTypes=JOB,WORKFLOW_INSTANCE,DEPLOYMENT,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION, enabledRecordTypes=, capacity=-1, timeToLiveInSeconds=-1, format=protobuf]
2020-04-28 09:30:54.547 [GatewayTopologyManager] [Broker-0-zb-actors-1] DEBUG io.zeebe.gateway - Received metadata change from Broker 0, partitions {1=LEADER} and terms {1=8}.
2020-04-28 09:30:54.555 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, EVENT=true, COMMAND=true, NULL_VAL=true, SBE_UNKNOWN=true}, acceptValueTypes={DEPLOYMENT=true, MESSAGE_SUBSCRIPTION=true, WORKFLOW_INSTANCE_SUBSCRIPTION=false, JOB_BATCH=false, VARIABLE=true, INCIDENT=true, TIMER=true, JOB=true, WORKFLOW_INSTANCE=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, WORKFLOW_INSTANCE_CREATION=false, MESSAGE=true, ERROR=true, WORKFLOW_INSTANCE_RESULT=false, VARIABLE_DOCUMENT=true, SBE_UNKNOWN=false, NULL_VAL=false}}
2020-04-28 09:30:54.564 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'elasticsearch'
2020-04-28 09:30:54.713 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.broker.exporter.elasticsearch - Exporter opened
2020-04-28 09:30:54.714 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Open exporter with id 'hazelcast'
Apr 28, 2020 9:30:54 AM com.hazelcast.instance.HazelcastInstanceFactory
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2020-04-28 09:30:55.152 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.instance.AddressPicker - [LOCAL] [dev] [3.12.6] Prefer IPv4 stack is true, prefer IPv6 addresses is false
2020-04-28 09:30:55.167 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.instance.AddressPicker - [LOCAL] [dev] [3.12.6] Picked [172.18.0.8]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
2020-04-28 09:30:55.219 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.system - [172.18.0.8]:5701 [dev] [3.12.6] Hazelcast 3.12.6 (20200130 - be02cc5) starting at [172.18.0.8]:5701
2020-04-28 09:30:55.220 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.system - [172.18.0.8]:5701 [dev] [3.12.6] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
2020-04-28 09:30:55.840 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator - [172.18.0.8]:5701 [dev] [3.12.6] Backpressure is disabled
2020-04-28 09:30:57.249 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.instance.Node - [172.18.0.8]:5701 [dev] [3.12.6] Creating MulticastJoiner
2020-04-28 09:30:57.677 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl - [172.18.0.8]:5701 [dev] [3.12.6] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
2020-04-28 09:30:57.695 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.internal.diagnostics.Diagnostics - [172.18.0.8]:5701 [dev] [3.12.6] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2020-04-28 09:30:57.730 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.core.LifecycleService - [172.18.0.8]:5701 [dev] [3.12.6] [172.18.0.8]:5701 is STARTING
2020-04-28 09:31:00.363 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.internal.cluster.ClusterService - [172.18.0.8]:5701 [dev] [3.12.6]

Members {size:1, ver:1} [
	Member [172.18.0.8]:5701 - 85e9dadf-8624-41b0-bfed-c41b1063c836 this
]

2020-04-28 09:31:00.426 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.core.LifecycleService - [172.18.0.8]:5701 [dev] [3.12.6] [172.18.0.8]:5701 is STARTED
2020-04-28 09:31:00.447 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  com.hazelcast.internal.partition.impl.PartitionStateManager - [172.18.0.8]:5701 [dev] [3.12.6] Initializing cluster partition table arrangement...
2020-04-28 09:31:00.474 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] INFO  io.zeebe.broker.exporter.hazelcast - Export records to ringbuffer with name 'zeebe' [head: 0, tail: -1, size: 0, capacity: 10000]
2020-04-28 09:31:00.893 [] [hz._hzInstance_1_dev.async.thread-2] INFO  com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask - [172.18.0.8]:5701 [dev] [3.12.6] Received auth from Connection[id=1, /172.18.0.8:5701->/172.18.0.10:33001, qualifier=null, endpoint=[172.18.0.10]:33001, alive=true, type=JAVA_CLIENT], successfully authenticated, principal: ClientPrincipal{uuid='92873663-ab26-4230-b658-7822547faf88', ownerUuid='85e9dadf-8624-41b0-bfed-c41b1063c836'}, owner connection: true, client version: 3.12.6
2020-04-28 09:40:54.378 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-0] DEBUG io.zeebe.logstreams.snapshot - We will skip taking this snapshot, because we haven't processed something yet.
```

What am I doing wrong ?

**Comment by PekopT** [comment]
finally i get it. 
for some reasons we can't name the service like 'zeebe_broker' 
I think wtf?!) but I renamed it to zeebe0 and it starts working....
crazy...

**Comment by Zelldon** [comment]
Thanks for the update. I think this is more docker related.

See for example https://github.com/docker/compose/issues/4475 or https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

I will close this. Feel free to re-open if you disagree.


You can also check out the docker-compose file under [docker/](https://github.com/zeebe-io/zeebe-simple-monitor/tree/master/docker)
