### ISSUE TITLE
Can't connect to Broker

### ISSUE THREAD

**Issue by OlivierAlbertini** [zeebe-io/zeebe-simple-monitor#25]
Hi

Env
laptop macbook pro mojave
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
go version go1.11.2 darwin/amd64

I successfully do the get started section of zeebe with the go tutorial (https://docs.zeebe.io/go-client/get-started.html) until it says to use the zeebe-simple-monitor

I run in docker the zeebe version 0.12.1

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                       NAMES
748a4823930d        camunda/zeebe:latest   "tini -- /usr/local/…"   32 hours ago        Up 37 minutes       0.0.0.0:26500->26500/tcp, 26501-26504/tcp   zeebe
```

 I got an error with the version 0.7.0 (zeebe-simple-monitor)

`Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [activity_instance]`

So I tried `java -jar zeebe-simple-monitor-0.6.0.jar`

I can connect to localhost:8080
I set the broker connection to localhost:26500
but It doesn't connect to the broker.
When I check to the zeebe container logs :

```
2018-11-03T21:15:00.857594400Z Nov 03, 2018 9:15:00 PM io.grpc.netty.NettyServerTransport notifyTerminated
2018-11-03T21:15:00.857665600Z INFO: Transport failed
2018-11-03T21:15:00.857685200Z io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 120000000000000000000000020000000000000000000000
2018-11-03T21:15:00.857702600Z 	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
2018-11-03T21:15:00.857728300Z 	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:318)
2018-11-03T21:15:00.859263700Z 	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
2018-11-03T21:15:00.859288900Z 	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
2018-11-03T21:15:00.859313000Z 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
2018-11-03T21:15:00.859354500Z 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
2018-11-03T21:15:00.859378900Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
2018-11-03T21:15:00.859402900Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-11-03T21:15:00.859427000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-11-03T21:15:00.859450900Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
2018-11-03T21:15:00.859474800Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
2018-11-03T21:15:00.859498700Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
2018-11-03T21:15:00.859533000Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
2018-11-03T21:15:00.859557300Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
2018-11-03T21:15:00.859581300Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
2018-11-03T21:15:00.859605200Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
2018-11-03T21:15:00.859629100Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
2018-11-03T21:15:00.859655400Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
2018-11-03T21:15:00.859679400Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
2018-11-03T21:15:00.859703300Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
2018-11-03T21:15:00.859727200Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2018-11-03T21:15:00.859751000Z 	at java.lang.Thread.run(Thread.java:748)
2018-11-03T21:15:00.859774700Z
```

Any help would be appreciated.

**Comment by saig0** [comment]
Hi @OlivierAlbertini ,

did you follow the [instructions](https://github.com/zeebe-io/zeebe-simple-monitor#how-to-run) at the page?

Before you can start the monitor-web-app and the broker, you must add the monitor-exporter to the broker. The exporter creates the database tables which are used by the monitor-web-app.

**Comment by OlivierAlbertini** [comment]
Thanks for your help! 
Yes, I do.

I think that I have a trouble to connect to h2 database. Since zeebe is a docker container, I guess that zeebe-simple-monitor which is an another docker container doesn't have access to the h2 database file.

Here my docker-compose 

```yaml
services:
  zeebe:
    image: camunda/zeebe:latest
    environment:
        - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
    volumes:
      - ./zeebe-simple-monitor-exporter-0.8.0.jar:/usr/local/zeebe/lib/zeebe-simple-monitor-exporter-0.8.0.jar
      - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
  h2:
    image: oscarfonts/h2
    ports:
      - 1521
      - 81
    links:
      - zeebe      
  monitor:
    image: camunda/zeebe-simple-monitor:latest
    ports:
      - "9000:8080"
    links:
      - zeebe
```
Can you help me to set the jdbc url for `camunda/zeebe-simple-monitor:latest` and `camunda/zeebe:latest` ?

Thanks a lot !

**Comment by Zelldon** [comment]
Hi @OlivierAlbertini I'm not an expert with the docker, but it should be possible via the docker volumes, or? So to say you link the h2 file into the monitor and zeebe docker, perhaps @menski can help?

Greets
Chris

**Comment by OlivierAlbertini** [comment]
Hi,

I successfully linked the zeebe broker to the database (url : `jdbc:h2:tcp://db:1521/zeebe-monitor`)
But I don't know how to specify to `camunda/zeebe-simple-monitor:latest` container how I can set this url (`jdbc:h2:tcp://db:1521/zeebe-monitor`). Can I specify an ENV ?

Thanks a lot !

**Comment by Zelldon** [comment]
Hi @OlivierAlbertini ,

cool!

Yes you can adjust the jdbc URL for the simple monitor, please take a look in the [configuration description](https://github.com/zeebe-io/zeebe-simple-monitor/tree/master/app#configuration).

Hope this helps.

Greets
Chris

**Comment by OlivierAlbertini** [comment]
Excellent, it works!

Are you interested if I create a PR in order to change (or add) the complete docker-compose. This docker-compose file, let you start zeebe borker and zeebe-simple-monitor with a hq database.
It will use your official images on docker hub. In this way, new people like me could just lunch docker-compose up for starting to use your product. It will be easier to use (no need to use maven, change zeebe.cfg.toml etc.. Everything will be provided).

What do you think ?

Again thanks for your help!

**Comment by Zelldon** [comment]
Glad to hear that, this would be my next question :D.
We would really appreciate it if you can create an PR for these changes.

Thanks @OlivierAlbertini

**Comment by OlivierAlbertini** [comment]
I will. Just checking with my company if I need to use my github company account or my personal is ok.

**Comment by RaviGithub555** [comment]
HI,
While deploy new workflow below issue getting, anybody help me please , i new user for zeebe
ERROR io.zeebe.broker.exporter.simple-monitor - Batch insert failed!
org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "RESOURCE_ VARCHAR(255)
