### ISSUE TITLE
Primary key violation in exporter 

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-simple-monitor#38]
When I include the exporter in my current broker 0.14.0 and run some samples I get: 

```
0:53:27.888 [exporter] [0.0.0.0:26501-zb-actors-0] ERROR io.zeebe.broker.exporter.simple-monitor - Batch insert failed!
org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.ACTIVITY_INSTANCE(ID_) VALUES ('2434e0c1-d6e3-4ccb-a21b-b366d5db1a0b', 67)"; SQL statement:
INSERT INTO ACTIVITY_INSTANCE (ID_, PARTITION_ID_, KEY_, INTENT_, WORKFLOW_INSTANCE_KEY_, ACTIVITY_ID_, SCOPE_INSTANCE_KEY_, PAYLOAD_, WORKFLOW_KEY_, TIMESTAMP_) VALUES ('2434e0c1-d6e3-4ccb-a21b-b366d5db1a0b', 0, 4710, 'ELEMENT_ACTIVATED', 4558, 'ServiceTask_0tnty4a', 4558, '{"orderId":"18","eventType":"OrderPaid"}', 3184, 1544607997368); [23505-197]
        at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:792) ~[zeebe-simple-monitor-exporter-0.9.0.jar:0.9.0]
        at io.zeebe.monitor.SimpleMonitorExporter.executeSqlStatementBatch(SimpleMonitorExporter.java:220) ~[zeebe-simple-monitor-exporter-0.9.0.jar:0.9.0]
        at io.zeebe.monitor.SimpleMonitorExporter.batchTimerExecution(SimpleMonitorExporter.java:211) ~[zeebe-simple-monitor-exporter-0.9.0.jar:0.9.0]
        at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:90) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [zb-util-0.14.0.jar:0.14.0]
        at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [zb-util-0.14.0.jar:0.14.0]
```

**Comment by saig0** [comment]
How can I reproduce the issue?

The primary key is a generated UUID. I'm wondering how a primary key violation can happen.

**Comment by berndruecker** [comment]
I have no idea - but I can also ot reproduce it after deleting the database ans start from scratch. Feel free to close from my perspective

**Comment by saig0** [comment]
Ok, so I'll close it for now.
