### ISSUE TITLE
Can't create instances

### ISSUE THREAD

**Issue by marc4gov** [zeebe-io/zeebe-simple-monitor#57]
Using jar file and regular broker 0.15 (no docker) I can deploy a workflow (demoProcess) but can't create instances. After this issue I can't deploy new workflows either, see log of broker:

```17:22:17.517 [exporter] [0.0.0.0:26501-zb-actors-1] INFO  io.zeebe.broker.exporter.simple-monitor - Start exporting to jdbc:h2:~/zeebe-monitor;AUTO_SERVER=TRUE.
Exception in thread "0.0.0.0:26501-zb-actors-0" java.lang.NoSuchMethodError: io.zeebe.exporter.record.value.WorkflowInstanceRecordValue.getScopeInstanceKey()J
	at io.zeebe.monitor.SimpleMonitorExporter.exportActivityInstance(SimpleMonitorExporter.java:389)
	at io.zeebe.monitor.SimpleMonitorExporter.exportWorkflowInstanceRecord(SimpleMonitorExporter.java:342)
	at io.zeebe.monitor.SimpleMonitorExporter.export(SimpleMonitorExporter.java:266)
	at io.zeebe.broker.exporter.stream.ExporterStreamProcessor$RecordExporter.executeSideEffects(ExporterStreamProcessor.java:230)
	at io.zeebe.logstreams.processor.StreamProcessorController.executeSideEffects(StreamProcessorController.java:320)
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87)
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:187)
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154)
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135)
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112)```

**Comment by Zelldon** [comment]
Hey @marc4gov,

thanks for the report.

This error is expected, since the latest version of the simple monitor is not fully compatible with the latest zeebe release (0.15).

The 0.15 Zeebe was released yesterday, but there is no new simple monitor release yet.
If you want to use the simple monitor please use the 0.14 zeebe version. Otherwise you need to wait until the next zeebe simple monitor release.

Greets,
Chris

**Comment by marc4gov** [comment]
Ok, thanks Chris
