### ISSUE TITLE
docker compose fails to run zeebe_monitor  - missing table [element_instance]

### ISSUE THREAD

**Issue by johanhallberg79** [zeebe-io/zeebe-simple-monitor#69]
I just pulled the latest code and then tried to start the docker compose by running `docker/run`. 

zeebe_monitor fails to start and I get the following exception:

```
zeebe_monitor | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [element_instance]
```

**Comment by Zelldon** [comment]
Hey,

thanks fot trying Zeebe and reporting this.

Could you please delete the database in your home folder, I think it is called something like `zeebe.db.*` and try to restart your monitor.

We currently have no update scripts and do not support starting with older databases.
Hope that helps.

Greets Chris

**Comment by johanhallberg79** [comment]
Hi,

I have some questions related to your answer:

1. Before doing the deployment I deleted all containers including stopped once. I also deleted the docker volumes. After that I modified the run script to build the zeebe-simple-monitor using the docker container:

```
#!/bin/bash

set -e

CONFIG_FILE=docker/local-config/docker-compose.yml
PULL_CMD="docker-compose -f $CONFIG_FILE pull"
UP_CMD="docker-compose up --build"

function rmContainers() {
  docker-compose -f $CONFIG_FILE rm -fv $SERVICE_NAME || true
}

CONTAINERS=(monitor zeebe db)

for i in "${!CONTAINERS[@]}"
do
   SERVICE_NAME=${CONTAINERS[$i]} rmContainers
done

$PULL_CMD

echo "Building project"
#mvn clean install
docker run -it --rm --name maven-zeebe-simple-monitor -v "$(pwd)":/usr/src/zeebe-simple-monitor -w /usr/src/zeebe-simple-monitor maven:3.3-jdk-8 mvn clean install
docker build -t camunda/zeebe-simple-monitor:latest -f app/Dockerfile app
echo "Done"

echo "copying jar"
cp exporter/target/zeebe-simple-monitor-exporter-*.jar docker/local-config/zeebe-simple-monitor-exporter.jar
echo "Done"

cd docker/local-config/
echo "starting containers"
$UP_CMD

cd ../..
```

Then I executed the docker/run script from the root folder. It launched the containers but I got the following output from zeebe_monitor:

```
zeebe_monitor | 
zeebe_monitor |   .   ____          _            __ _ _
zeebe_monitor |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
zeebe_monitor | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
zeebe_monitor |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
zeebe_monitor |   '  |____| .__|_| |_|_| |_\__, | / / / /
zeebe_monitor |  =========|_|==============|___/=/_/_/_/
zeebe_monitor |  :: Spring Boot ::        (v2.1.2.RELEASE)
zeebe_monitor | 
zeebe_monitor | 2019-06-09 19:58:25.044  INFO 1 --- [           main] io.zeebe.monitor.ZeebeSimpleMonitorApp   : Starting ZeebeSimpleMonitorApp v0.15.0-SNAPSHOT on b04c5860298a with PID 1 (/usr/local/zeebe-simple-monitor.jar started by root in /)
zeebe_monitor | 2019-06-09 19:58:25.050  INFO 1 --- [           main] io.zeebe.monitor.ZeebeSimpleMonitorApp   : No active profile set, falling back to default profiles: default
zeebe_monitor | 2019-06-09 19:58:26.917  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
zeebe_monitor | 2019-06-09 19:58:27.147  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 208ms. Found 10 repository interfaces.
zeebe_monitor | 2019-06-09 19:58:27.961  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$9819f6f2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
zeebe_monitor | 2019-06-09 19:58:28.691  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
zeebe_monitor | 2019-06-09 19:58:28.751  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
zeebe_monitor | 2019-06-09 19:58:28.752  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
zeebe_monitor | 2019-06-09 19:58:28.775  INFO 1 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
zeebe_monitor | 2019-06-09 19:58:29.093  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
zeebe_monitor | 2019-06-09 19:58:29.093  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3905 ms
zeebe_monitor | 2019-06-09 19:58:29.485  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
zeebe_monitor | 2019-06-09 19:58:29.634  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
zeebe_monitor | 2019-06-09 19:58:29.789  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
zeebe_monitor | 	name: default
zeebe_monitor | 	...]
zeebe_monitor | 2019-06-09 19:58:29.991  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.7.Final}
zeebe_monitor | 2019-06-09 19:58:29.995  INFO 1 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
zeebe_monitor | 2019-06-09 19:58:30.359  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
zeebe_monitor | 2019-06-09 19:58:30.850  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
zeebe_monitor | 2019-06-09 19:58:32.486  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [element_instance]
zeebe_monitor | 2019-06-09 19:58:32.486  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
zeebe_monitor | 2019-06-09 19:58:32.520  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
zeebe_monitor | 2019-06-09 19:58:32.526  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
zeebe_monitor | 2019-06-09 19:58:32.554  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
zeebe_monitor | 
zeebe_monitor | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
zeebe_monitor | 2019-06-09 19:58:32.565 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
zeebe_monitor | 
zeebe_monitor | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [element_instance]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:853) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
zeebe_monitor | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
zeebe_monitor | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
zeebe_monitor | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
zeebe_monitor | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
zeebe_monitor | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
zeebe_monitor | 	at io.zeebe.monitor.ZeebeSimpleMonitorApp.main(ZeebeSimpleMonitorApp.java:49) [classes!/:0.15.0-SNAPSHOT]
zeebe_monitor | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
zeebe_monitor | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
zeebe_monitor | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
zeebe_monitor | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
zeebe_monitor | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [zeebe-simple-monitor.jar:0.15.0-SNAPSHOT]
zeebe_monitor | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [zeebe-simple-monitor.jar:0.15.0-SNAPSHOT]
zeebe_monitor | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [zeebe-simple-monitor.jar:0.15.0-SNAPSHOT]
zeebe_monitor | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [zeebe-simple-monitor.jar:0.15.0-SNAPSHOT]
zeebe_monitor | Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [element_instance]
zeebe_monitor | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:402) ~[spring-orm-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377) ~[spring-orm-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	... 24 common frames omitted
zeebe_monitor | Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [element_instance]
zeebe_monitor | 	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:121) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:191) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:310) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:939) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
zeebe_monitor | 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57) ~[spring-orm-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390) ~[spring-orm-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
zeebe_monitor | 	... 28 common frames omitted
zeebe_monitor | 
zeebe_monitor exited with code 1
```

The zeebe_monitor restarts over and over again giving me the same error. The other containers starts up fine. Output from docker ps:

```
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                          PORTS                                                               NAMES
552ff5fd23ad        camunda/zeebe-simple-monitor:latest   "java -jar /usr/loca  "   12 minutes ago      Restarting (1) 12 seconds ago                                                                       zeebe_monitor
d64285959464        local-config_zeebe                    "tini -- /usr/local/  "   12 minutes ago      Up 12 minutes                   0.0.0.0:5701->5701/tcp, 0.0.0.0:26500->26500/tcp, 26501-26504/tcp   local-config_zeebe_1
1cf5a2195ad1        oscarfonts/h2                         "/bin/sh -c 'java -c  "   12 minutes ago      Up 12 minutes                   0.0.0.0:81->81/tcp, 0.0.0.0:1521->1521/tcp                          zeebe_db
```

So, my first question: 
Why do I have to delete the database when starting off from a clean install using docker-compose? Shouldn't I already have a clean database?

2. If I need to delete the database, where exactly is it located? In which container? Is it mounted from my host? If so, what is the path to it?

3. Have you tried this yourself? Is the docker compose working for you?

4. I also noticed that you have two different compose files in your project. I am using the one in zeebe-simple-monitor/docker folder. I could see that the other one in the app folder doesn't contain a container for the database. Should both of them work or should I change to the one in the app/docker-compose folder?

BR,
Johan

**Comment by Zelldon** [comment]
Hey,

sorry over read that you using the docker-compose file.

I think the problem is that the image `camunda/zeebe:latest` is not the latest release. I think we have to fix this. Could you please edit the `docker/local-config/Dockerfile` and use `camunda/zeebe:0.18.0` and the hazelcast exporter version 0.3.0.

Regarding to your questions:

 1. If you deleted the old images then it should be fine.
 2. I think this is only necessary if you build and run it by hand
 3. I tried this now and it seems that the versions mismatch. Sometimes the order of the starting containers is not correct and the monitor starts before the exporter creates the tables, then you see this exception. But after some time this should be fine, since the monitor tries again.
 4. I think the one in the `app` folder is outdated.

Hope this helps

Greets
Chris

**Comment by johanhallberg79** [comment]
Hi,

Thanks for your help Chris! Changing the versions solved the problem. I really suggest that you either make a note of this in the readme or update the Dockerfile so that others don't run into the same problem.

Do you want me to close this issue now or will you keep it open until it has been fixed?

BR,
Johan

**Comment by Zelldon** [comment]
I'm glad that this worked. Let's keep this open until we fixed this.
